name: "Check PR Approval"

on:
 pull_request_review:
   types: [submitted, edited]

# https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-review-event-pull_request_review
#on:
#  pull_request_review:
#    types: [submitted, edited, dismissed]

jobs:

##
## Running the next-ci-action
##
  pr_approval:
    runs-on: ubuntu-latest
    steps:
     # ..........................................
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ tojson(github) }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}
       run: |
          echo "$GITHUB_CONTEXT"
          echo $ENVIRONMENT
     # ..........................................          
     - uses: actions/checkout@v2
     # need to regenerate everything before merge...
     #    regenerate NEXT.json [can have multiple PRs not merged at the same time...]
     - name: Checking Pull Request Approval
       uses: next-cpan/next-ci-action@master
       with:
          stage: pr_approval
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

# pull_request.review.state: approved
# "event_name": "pull_request_review",
# event.action: submitted