name: "Check Pull Request"

on:
  pull_request:
    types: [opened,reopened,edited]
    branches: ["p5"]
#  pull_request_review:
#    types: [submitted]

# name: automerge
# on:
#   pull_request:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}

jobs:

##
## lint Checks
##

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "running lint..."
        run: |
          echo "FIXME Plug Lint here"
          # check if there is no conflict with the namespaces
          true

##
## Running the test suite
##
  tests:
    name: "Testing with cnext"
    needs: lint
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     node: ['5.30', '5.28']
    steps:
      # no need to checkout
      - name: using install-with-cnext
        uses: perl-actions/install-with-cnext@cnext-ci
    # FIXME check the installation of module

##
## Running the next-ci-action
##
  merge:
    runs-on: ubuntu-latest
    needs: tests
    if: always() # set always
    steps:
      - uses: actions/checkout@v2
        # run this action to get workflow conclusion
        # You can get conclusion by env (env.WORKFLOW_CONCLUSION)
        # https://github.com/marketplace/actions/workflow-conclusion-action
      - uses: technote-space/workflow-conclusion-action@v1.1.1
      - name: Checking Pull Request
        uses: next-cpan/next-ci-action@master
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }} # neutral, success, cancelled, timed_out, failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        #if: env.WORKFLOW_CONCLUSION == 'failure'

# if: ${{ always() }}
# if: ${{ cancelled() }}
# if: ${{ success() }}
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

# if: failure()
# if: startsWith(github.ref, 'refs/tags/v')
#    if: always() # set always
